FROM node:22.14.0

WORKDIR /usr/src/app

COPY server/package.json ./
RUN corepack enable && pnpm install

# Copy server sources after pnpm install
COPY server/ ./

EXPOSE 5000

CMD ["pnpm", "run", "dev"]
